template_dir: Abort installation if requested
Abort installation of the SDK if users answers "no"
to "Do you want to continue?"

Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>

diff --git a/scripts/template_dir b/scripts/template_dir
--- a/scripts/template_dir
+++ b/scripts/template_dir
@@ -126,6 +126,10 @@ if [ -d $target_sdk_dir ]; then
 		read_confirm
 	    if [ "$confirm" = "y" -o "$confirm" = "Y" ]; then
 		    rm -rf $target_sdk_dir/*
+		else
+		    # Abort the installation
+		    echo "SDK installation aborted!"
+		    exit 1
 		fi
 	fi
 else
